development:
  adapter: sqlite3
  database: data/pocketspruce.db

test:
  adapter: sqlite3
  database: data/pocketspruce.db

production:
  adapter: postgresql
  encoding: unicode
  pool: 5
  database: <%= ENV['DATABASE'] || "pocketspruce" %>
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host: <%= ENV['DATABASE_HOST'] %>
  port: <%= ENV['DATABASE_PORT'] %>
